@startuml
alt Singola Risorsa
	"Sender" -> "Receiver" : Aggiorna Singola Risorsa [PUT]
	"Receiver" --> "Sender" : PUT Response
else Transaction, Batch
	"Sender" -> "Receiver" : Aggiornamento Dossier Farmaceutico (Bundle) [POST]
	"Receiver" --> "Sender" : POST Response
end
@enduml