@startuml
alt Transaction, Batch
	"Sender" -> "Receiver" : Alimentazione Dossier Farmaceutico (Bundle) [POST]

else Singola Risorsa
	"Sender" -> "Receiver" : Invia Singola Risorsa [POST]
end
	"Receiver" --> "Sender" : POST Response
@enduml