@startuml
alt Consultazione per identificativo di prescrizione
	"Consumer" -> "Provider" : Consultazione per order id (operation) [GET/POST]
	"Provider" --> "Consumer" : Operation Response [GET/POST]
else Altre consultazioni 
	"Consumer" -> "Provider" : altre consultazioni (FHIR search) [GET/POST]
	"Provider" --> "Consumer" : GET/POST search response [Search Bundle]
end
@enduml